# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
jobs:
  # Single deploy job since we're just deploying
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: gl.umbc.edu
          username: ${{secrets.ftp_username}}
          password: ${{ secrets.ftp_password }}
          local_path: './*'
          remote_path: '/afs/umbc.edu/users/a/t/atalwar1/pub/swe2023/project'
          sftp_only: true
